### ISSUE TITLE
404 on the new update

### ISSUE THREAD

**Issue by juxuanu** [flathub/com.getpostman.Postman#111]
```
        ID                              Branch         Op         Remote          Download
 1. [✗] com.getpostman.Postman          stable         u          flathub         1,0 kB / 130,8 MB

Error: While downloading https://dl.pstmn.io/download/version/8.11.0/linux64: Server returned status 404: Not Found
```

**Comment by ghisvail** [comment]
Just keep retrying. Hopefully they have not permanently moved releases
somewhere else.

**Comment by GammaGames** [comment]
I don't even see 8.11.0 available on their site. No release notes either

**Comment by juxuanu** [comment]
https://dl.pstmn.io/download/latest/linux64

**Comment by juxuanu** [comment]
> I don't even see 8.11.0 available on their site. No release notes either

Latest seems v8.10.0

**Comment by ghisvail** [comment]
They must have made a release and reverted it later. Not the first time upstream messes up with their releases.
