### ISSUE TITLE
Error: While downloading https://dl.pstmn.io/download/version/...

### ISSUE THREAD

**Issue by zobzn** [flathub/com.getpostman.Postman#124]
```
Error: While downloading https://dl.pstmn.io/download/version/8.12.2/linux64: Server returned status 404: Not Found
```

Looks like right now the latest version for linux is 8.11.1

```
$ curl -I https://dl.pstmn.io/download/latest/linux64
HTTP/2 200 
content-type: application/gzip
content-length: 129557197
date: Fri, 17 Sep 2021 12:35:57 GMT
...
content-disposition: attachment; filename=Postman-linux-x86_64-8.11.1.tar.gz
...
```

**Comment by ghisvail** [comment]
Postman releases are a farce, sadly.

**Comment by nguyenhai97** [comment]
why would you submit the commit for 8.12.2 already, on the home page it only let me download the 8.12.1 version and since flatpak won't allow me to install 8.12.1 any more I was unable to install postman via flatpak for sure :(

**Comment by ghisvail** [comment]
> why would you submit the commit for 8.12.2 already

Because our CI process checks daily whether a new release has been uploaded and rebuild the Flatpak automatically. That process breaks if upstream decides to release a new version and subsequently retract it, which is what happened with version `8.12.2`.

> I was unable to install postman via flatpak for sure :(

That's unfortunate, indeed. Postman sucks with updates.

**Comment by ghisvail** [comment]
Actually, it looks like the whole 8.12.x tree is gone, so I'd have to revert back to version `8.11.1`. Unless they moved their files somewhere else which is entirely possible given their track record.

**Comment by ghisvail** [comment]
For the record, monitoring for new versions now use the release notes instead of the Postman public API which was responsible for this issue to begin with (see #128). We'll see whether it proves more reliable long term.

**Comment by zobzn** [comment]
thanks for fixing this up

**Comment by nguyenhai97** [comment]
I appreciate the effort author put to maintain this package, but this issue here help me found my true love with `Insomnia`, it support theme, keybindind, plugin, ... it did lack some of feature that postman has to offer but I think it will be filled in near future
