### ISSUE TITLE
Import/Export fails when following a link to a folder

### ISSUE THREAD

**Issue by lcapalbo** [flathub/com.getpostman.Postman#168]
Try to import/export a collection or environment, then select a symlink to a folder and try to open it to select a file within.

Postman tries to import/write the symlink as a file, instead of navigating

**Comment by ghisvail** [comment]
Please report this upstream.

**Comment by lcapalbo** [comment]
Thanks @ghisvail, I reported this here as the compressed version of Postman from their site works fine, I'm only having this issue with the flatpak.
I was going to report it upstream but then I found a report already exists https://github.com/postmanlabs/postman-app-support/issues/5740 about both flatpak and snap with the same issue

**Comment by lcapalbo** [comment]
I edited the `com.getpostman.Postman.yaml` manifest setting the `finish-args:` from `- --filesystem=home` to `- --filesystem=host` and that fixed the issue, so it's really a permission problem with flatpak Postman being unable to access anything outside the user' s home. Any symlink to such a target is processed as a standard file and tried to read/write on import/export.

I understand there may be interest in leaving things as they are (and just close this ticket), for security reasons, but it's a shame its experienced as a bug by the final user, instead of having some warning like "Postman is currently sandboxed to the user directory only" or something like that, but that would probably be for the flatpak runtime side.. I'll comment that upstream just in case.

**Comment by ghisvail** [comment]
Feel free to use `flatseal` to tailor the app permissions to your needs.

Indeed, Postman has no business getting full `host` access by default.

**Comment by ijash** [comment]
Just wanted to add, if you use [flatseal](https://github.com/tchx84/flatseal), which is a permission utility for flatpak, toggling this solves the problem:

![image](https://user-images.githubusercontent.com/30673286/153717215-62b3a81f-511d-4044-aef0-2bac4682333a.png)

Select Postman and just scroll down on the right pane until you find **FIle System**, and toggle **All system files**
