### ISSUE TITLE
Opening postman:// links with xdg-open stopped working

### ISSUE THREAD

**Issue by christianfosli** [flathub/com.getpostman.Postman#187]
### Steps to reproduce

* Open Authorization tab and fill out options to get an oauth2 access token with grant type "Authorization code with PKCE"
* Check the "Authorize using browser" checkbox
* Click "Get New Access Token" button
* The browser opens, authentication appears to succeed and redirects to https://oauth.pstmn.io/v1/callback

**Expected**: Postman opens the pop-up and gets token

**Actual**: It appears nothing happens. Postman keeps waiting for callback indefinitely or until I click "Cancel".

### Error details

To get better error logs I tried opening a postman:// url using xdg-open from the terminal:

```shell
[cfosli ~]$ xdg-open "postman://app/oauth2/callback?code=some-authorization-code&scope=openid&session_state=some-session-state"
[cfosli ~]$ sh: line 1: --no-sandbox: command not found
[4:0627/220017.171528:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/extra/Postman/chrome-sandbox is owned by root and has mode 4755.
```

I think this worked earlier, but I didn't investigate enough to find out which version it possibly broke with. 

### System info

* OS: Fedora Linux 36
* Postman version: 9.19.0

```shell
[cfosli ~]$ flatpak info com.getpostman.Postman

Postman - Postman is a complete API development environment.

          ID: com.getpostman.Postman
         Ref: app/com.getpostman.Postman/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 9.19.0
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 4.0 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 2ac05f503f3e0e24fd95e2b4f98e1735a949293165787a08c897344f6d1931db
      Parent: aedc09acc9afb359abb05c46351e6aabbfba1333f80ea6e5efe2a88168ad2c14
     Subject: Update Postman.tar.gz to 9.19.0 (bf36c0e6)
        Date: 2022-05-26 08:44:15 +0000
```

### Related issues

It seems vscode flatpak had a similar issue. See https://github.com/flathub/com.visualstudio.code/issues/223

**Comment by DanielNoga** [comment]
I can confirm, same issue on openSUSE, I cannot login into Postman as browser does not open

**Comment by ghisvail** [comment]
I don't use this feature so I can't really trace this regression. Feel free to try again with the latest version.

**Comment by christianfosli** [comment]
> I don't use this feature so I can't really trace this regression. Feel free to try again with the latest version.

Gotcha. I still get the same behavior with the latest version (Postman 9.31.0, org.freedesktop.Platform/SDK 21.08).

**Comment by christianfosli** [comment]
>  I still get the same behavior with the latest version (Postman 9.31.0, org.freedesktop.Platform/SDK 21.08).

And same behavior with org.freedesktop.Platform/SDK 22.08 (#195)

**Comment by jnv** [comment]
This is still the issue in Fedora 37. Looks like in case of VS Code they fixed this issue using Zypak?

**Comment by jnv** [comment]
I opened a PR to fix this: https://github.com/flathub/com.getpostman.Postman/pull/219
