### ISSUE TITLE
Missing Deskop files on Fedora

### ISSUE THREAD

**Issue by lucabotti** [flathub/com.getpostman.Postman#19]
Hi,
after installing Postman (through Gnome Software) I am not able to start it via desktop icon, which is missing.

**Comment by TingPing** [comment]
If its your first flatpak you have to logout once.

**Comment by lucabotti** [comment]
Not the first flatpak:

Postman - Postman is a complete API development environment.
>>                           com.getpostman.Postman                    6.7.3
>>        stable     x86_64     flathub     system
>
> Skype - Call and message skype users, with video chat support
>>                            com.skype.Client
>> 8.34.0.78     stable     x86_64     flathub     system
>
> Slack - Chat with your team
>>                            com.slack.Slack                           3.3.7
>>        stable     x86_64     flathub     system
>
> Spotify - Online music streaming service
>>                             com.spotify.Client
>> 1.1.0.237     stable     x86_64     flathub     system
>
> Steam - Manage and play games distributed by Steam
>>                             com.valvesoftware.Steam
>>          stable     x86_64     flathub     system
>
> Freedesktop.org Application Platform version 18.08 - Shared libraries
>> provided by freedesktop.org     org.freedesktop.Platform
>>                 18.08      x86_64     flathub     system
>
> i386
>>                             org.freedesktop.Platform.Compat.i386
>>         18.08      x86_64     flathub     system
>
> Intel VAAPI Driver - Intel driver for hardware accelerated video decoding
>> and playback                org.freedesktop.Platform.VAAPI.Intel
>>         1.6        x86_64     flathub     system
>
> Intel
>>                            org.freedesktop.Platform.VAAPI.Intel
>>         18.08      x86_64     flathub     system
>
> FFmpeg extension - Add support for aac, mpeg4 and h264
>>                             org.freedesktop.Platform.ffmpeg
>>          1.6        x86_64     flathub     system
>
> html5-codecs
>>                             org.freedesktop.Platform.html5-codecs
>>          18.08      x86_64     flathub     system
>
> GNOME Application Platform version 3.28 - Shared libraries used by GNOME
>> applications                 org.gnome.Platform
>>           3.28       x86_64     flathub     system
>
> GNOME Application Platform version 3.30 - Shared libraries used by GNOME
>> applications                 org.gnome.Platform
>>           3.30       x86_64     flathub     system
>
> Inkscape - Vector Graphics Editor
>>                            org.inkscape.Inkscape
>>  0.92.4        stable     x86_64     flathub     system
>
> Adwaita theme - Adwaita widget theme matching the GNOME adwaita theme
>>                            org.kde.KStyle.Adwaita
>>         5.12       x86_64     flathub     system
>
> Adwaita theme - Adwaita widget theme matching the GNOME adwaita theme
>>                            org.kde.KStyle.Adwaita
>>         5.9        x86_64     flathub     system
>
> KDE Application Platform - Shared libraries used by KDE applications
>>                             org.kde.Platform
>>         5.12       x86_64     flathub     system
>
> KDE Application Platform version master - Shared libraries used by KDE
>> applications                   org.kde.Platform
>>             5.9        x86_64     flathub     system
>
> QGnomePlatform - Qt Platform Theme aimed to accommodate GNOME settings
>>                             org.kde.PlatformTheme.QGnomePlatform
>>         5.12       x86_64     flathub     system
>
>
>
Il giorno dom 24 feb 2019 alle ore 18:38 Patrick <notifications@github.com>
ha scritto:

**Comment by gombosg** [comment]
Interesting, I have a desktop file on Fedora.

**Comment by ghisvail** [comment]
Same here. Not sure what to do.

**Comment by ghisvail** [comment]
I am closing this issue as I see no further action possible.
