### ISSUE TITLE
Update to Postman 10

### ISSUE THREAD

**Issue by mrvik** [flathub/com.getpostman.Postman#197]
Hello.

The new Postman version (10) has been out for a while, but the flatpak didn't update. Is there anything blocking the update?

**Comment by ghisvail** [comment]
> Is there anything blocking the update?

The Postman devs themselves. The [stable version](https://dl.pstmn.io/api/version/latest?platform=linux64&channel=stable ) for Linux is still `9.31.0` at this time.

**Comment by Anifyuli** [comment]
I wish Postman in Flatpak version is up-to-date same as latest version of Postman

**Comment by ghisvail** [comment]
Fixed by #199
