### ISSUE TITLE
404 Not Found trying to update to 10.9.0

### ISSUE THREAD

**Issue by ronwilhoite** [flathub/com.getpostman.Postman#211]
$ flatpak update
Looking for updates…

        ID                              Branch          Op          Remote          Download
 1. [✗] com.getpostman.Postman          stable          u           flathub         1.0 kB / 168.9 MB

Error: While downloading https://dl.pstmn.io/download/version/10.9.0/linux64: Server returned status 404: Not Found
Updates complete.
error: There were one or more errors

**Comment by dirthsj** [comment]
Postman unreleased version 10.9.0 after the auto-updater picked it up. If you have 10.8.0 you have the latest version currently available.

**Comment by ghisvail** [comment]
@postmanlabs have very questionable release practices. Sadly, issues like this still happen in 2023.
