### ISSUE TITLE
Postman fails to install/update

### ISSUE THREAD

**Issue by buzzcz** [flathub/com.getpostman.Postman#265]
When trying to install Postman on Fedora 40, I get an error: `Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256`

The whole installation output is this:
```
flatpak install com.getpostman.Postman
Looking for matches…

com.getpostman.Postman permissions:
    ipc           network      pulseaudio      x11      dri      file access [1]      dbus access [2]
    tags [3]

    [1] home
    [2] com.canonical.AppMenu.Registrar
    [3] proprietary


        ID                                           Branch           Op           Remote            Download
 1. [✗] org.freedesktop.Platform.openh264            2.2.0            i            flathub           614,6 kB / 944,3 kB
 2. [✗] com.getpostman.Postman                       stable           i            flathub           141,4 MB / 144,7 MB

Warning: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
Error: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
error: Failed to install com.getpostman.Postman: Error deploying: While trying to apply extra data: apply_extra script failed, exit status 256
```

I had it installed previously and the update process would fail the same way. I uninstalled it and tried to install it again, but with no luck.

**Comment by Victor239** [comment]
Have been getting the same error, can't update it.

**Comment by ghisvail** [comment]
They probably yanked their release once again :roll_eyes: 

Perhaps a good opportunity to try an opensource alternative such as Hoppscotch or Insomnia?

**Comment by LBWright** [comment]
Also have the same error. Unfortunately. I'm not even able to uninstall because I'm getting this error now when I uninstall
![image](https://github.com/user-attachments/assets/6578d377-6cee-488b-b40e-c041c4e7cc98)
