### ISSUE TITLE
Images/files not uploaded because of sandbox

### ISSUE THREAD

**Issue by NeroVanbiervliet** [flathub/com.getpostman.Postman#29]
When adding a file to the body of a request, postman shows a warning: 
> The file resides outside the working directory. Collaborators might not have the same file path.

When performing the request, the file is not added (`content-length` is zero).

I think this is due to the sandboxing of flatpak. Additional permissions should be added.

**Comment by ghisvail** [comment]
The home directory is already exposed with `--filesystem=home`.

Not sure what's going on here.

**Comment by NeroVanbiervliet** [comment]
You're right! I forgot to fill in the `image` key in the formdata.
Sorry for the noise, I'm closing this.

**Comment by ghisvail** [comment]
No worries. Mistakes happen.

Le sam. 1 juin 2019 à 13:45, NeroVanbiervliet <notifications@github.com> a
écrit :
