### ISSUE TITLE
new version available

### ISSUE THREAD

**Issue by kostadinnm** [flathub/com.getpostman.Postman#40]
Hey, there's a new version - 7.9.0:
![2019-10-15_14-02](https://user-images.githubusercontent.com/18436405/66826199-948bec00-ef54-11e9-8c7b-d89bc7b25dfc.png)

**Comment by ghisvail** [comment]
Great, thanks for the heads up.

Feel free to submit a PR to update the flatpak.

Le mar. 15 oct. 2019 à 13:03, Kostadin Markov <notifications@github.com> a
écrit :
