### ISSUE TITLE
Any updates on new Postman version ?

### ISSUE THREAD

**Issue by nhubaotruong** [flathub/com.getpostman.Postman#61]
Hi,

Postman is now version 7.36.0. I haven't seen any update on flathub.

Are things okay? I was trying to submit a manual update, but I don't have the permission.

Thanks.

**Comment by ghisvail** [comment]
Postman keeps breaking the page where from the new version is parsed :angry:

**Comment by nhubaotruong** [comment]
Are you using some kind of auto update detector ?

**Comment by ghisvail** [comment]
I use a parser on the download page to fetch the latest version advertised, and then build the canonical download URL from it. Upstream has got a history of "moving things around", breaking this process as a result. Now it seems information is hidden within layers of iframe and javascript, sadly.

**Comment by nhubaotruong** [comment]
is it possible to parse the latest version from an api,
[https://dl.pstmn.io/api/version/latest?platform=linux64&channel=stable](https://dl.pstmn.io/api/version/latest?platform=linux64&channel=stable) seems pretty straight forward to me.

**Comment by ghisvail** [comment]
> is it possible to parse the latest version from an api

Maybe. Sounds like a better solution in the long run. Thanks for your suggestion.

**Comment by nhubaotruong** [comment]
I look forward to hearing good news from you. I'll close this issue now.

**Comment by ghisvail** [comment]
It worked. Cheers!
