### ISSUE TITLE
Install spams an ownership issue for every file in package

### ISSUE THREAD

**Issue by sebastianlacuesta** [flathub/com.getpostman.Postman#82]
When installing or upgrading Postman, for every file inside the flatpak I get following message:

`tar: <path/of/every/file/here: Cannot change ownership to uid 1001, gid 1002: Operation not permitted`

**Comment by ghisvail** [comment]
Sadly, I can't reproduce your issue. I have re-installed Postman and launched it with `flatpak run`. I am not seeing any ownership errors in the logs and the app launches just fine.

**Comment by sebastianlacuesta** [comment]
I have this issue if I install as root system wide. Not in my normal user as I could see.

**Comment by Leeo97one** [comment]
Same for me with each update. I guess adding the `--no-same-owner` option to `tar -xf Postman.tar.gz` in the `com.getpostman.Postman.yaml` file should fix the issue.

**Comment by ghisvail** [comment]
@Leeo97one feel free to submit a PR with what you propose :+1:
